#pragma once

#include "./leep_music_v2.h"
#include "./leep_custom_keycodes_v2.h"
#include "./leep_layers_v2.h"
#include "./leep_tap_dance_v2.h"
#include "./leep_alt_v2.h"
#include "./leep_aliases_v2.h"
#include "./leep_google_v2.h"
#include "./leep_url_v2.h"
#include "./leep_workspace_v2.h"
#include "./leep_outlook_v2.h"
#include "./leep_modifiers_v2.h"
#include "./leep_slack_v2.h"
#include "./leep_shift_v2.h"
#include "./leep_record_v2.h"
#include "./leep_color_v2.h"
#include "./leep_oneshot_v2.h"
